### ISSUE TITLE
Deployment not taking?

### ISSUE THREAD

**Issue by zware** [berkerpeksag/cpython-emailer-webhook#12]
I'm not sure our deployments are working correctly; I haven't yet seen a checkin email for the 3.9 branch.

**Comment by Mariatta** [comment]
Through Heroku I could see a deploy on Sep 8. But it's been erroring out:

Latest Heroku log:

```
2020-09-14T19:48:17.883235+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/" host=psf-webhook-mailer.herokuapp.com request_id=f9249142-3442-4976-91a6-e29242065dff fwd="140.82.115.250" dyno=web.1 connect=1ms service=30003ms status=503 bytes=0 protocol=https
2020-09-14T19:48:17.980065+00:00 app[web.1]: Traceback (most recent call last):
2020-09-14T19:48:17.980114+00:00 app[web.1]: File "/app/mailer.py", line 127, in handler
2020-09-14T19:48:17.980116+00:00 app[web.1]: result = await PushEvent(client, smtp, request).process()
2020-09-14T19:48:17.980218+00:00 app[web.1]: File "/app/mailer.py", line 119, in process
2020-09-14T19:48:17.980219+00:00 app[web.1]: _, response = await send_email(self.smtp, message)
2020-09-14T19:48:17.980276+00:00 app[web.1]: File "/app/mailer.py", line 87, in send_email
2020-09-14T19:48:17.980279+00:00 app[web.1]: await server.connect()
2020-09-14T19:48:17.980289+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/aiosmtplib/connection.py", line 185, in connect
2020-09-14T19:48:17.980290+00:00 app[web.1]: await self._connect_lock.acquire()
2020-09-14T19:48:17.980294+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/asyncio/locks.py", line 192, in acquire
2020-09-14T19:48:17.980295+00:00 app[web.1]: await fut
2020-09-14T19:48:17.980424+00:00 app[web.1]: concurrent.futures._base.CancelledError
```

**Comment by Mariatta** [comment]
See thread in https://mail.python.org/archives/list/python-dev@python.org/message/NLLZVN7GBRVN3UCK7AORNSUFWQCOJX67/

When I look at the webhook deliveries to this endpoint, all the deliveries have been erroring since the deploy on Sep 8.

**Comment by Mariatta** [comment]
A couple ideas here:
- If the `send_email` coroutine is taking a long time, perhaps it should be executed as a ``celery``` task? 
- maybe look into using Python 3.8 runtime, and update the dependency versions

**Comment by Mariatta** [comment]
I've created PR for sending the email using celery task.

**Comment by berkerpeksag** [comment]
Thanks for the report! This has been working fine for over a year without any issues so I suspect there is an issue with updated dependencies.

Latest deploy:

```
aiohttp-2.3.10
aiosmtplib-1.0.6
async-timeout-3.0.1
chardet-3.0.4
idna-2.8
idna-ssl-1.1.0
multidict-4.5.2
yarl-1.3.0
```

Latest working deploy from Jun 4, 2019:

```
aiohttp-1.3.1
aiosmtplib-1.0.0
async-timeout-3.0.1
chardet-3.0.4
idna-2.8
multidict-4.5.2
py-1.8.0
pytest-3.1.3
pytest-aiohttp-0.1.3
yarl-0.18.0
```

Using Celery to send emails is definitely a better way (thanks!), but the underlying issue might be in one of the dependencies. I'll try to downgrade aiosmtplib first.

**Comment by berkerpeksag** [comment]
Downgrading aiosmtplib to 1.0.0 seems to be worked. I'll re-redeliver all failed deliveries.

**Comment by berkerpeksag** [comment]
All payloads have been redelivered.

**Comment by Mariatta** [comment]
Thanks! Yes we got the emails now.
